### ISSUE TITLE
Is there any way to get homework assignment(not just Colab)?

### ISSUE THREAD

**Issue by dwang55** [hdvvip/CS224W_Winter2021#1]
Thanks for sharing! I am interested in this course too, and I found that there are 3 homework assignments in this course. However these assignments seem to have no links on the course website. Is there any way to get them?

**Comment by hdvvip** [comment]
Unfortunately, at the moment this comment is written, we can't get access to the HW of the Spring 2021 version. However, you can access the HW of Fall 2019 version http://snap.stanford.edu/class/cs224w-2019/
There are also plenty of solutions for Fall 2019's HW online
