### ISSUE TITLE
Colab_4, error about HeteroGraph

### ISSUE THREAD

**Issue by hao-zheng-uoa** [hdvvip/CS224W_Winter2021#3]
When I was running the following codes,
```
from deepsnap.hetero_graph import HeteroGraph

hete = HeteroGraph(G_orig)
```
I got the error, saying
`TypeError: Unknown type color in edge attributes.`

However, in the previous lines, there is a line like:
`colors = nx.get_edge_attributes(G,'color').values()`
and it works. It means G has the attributes 'color'. So I am confused, what should I do?

**Comment by hdvvip** [comment]
![Selection_410](https://user-images.githubusercontent.com/42698038/122700212-d6386400-d218-11eb-81ad-2aabf5ddd330.png)
I could run that line of code without any problem (attached image)
I suggest you to restart the session and run from top to bottom again.
Try to run the Colab_4 on Google Colab, I attached below the code you need to install on Google Colab to run the Colab_4
![Selection_411](https://user-images.githubusercontent.com/42698038/122700627-a76ebd80-d219-11eb-9ef3-e5fd8301433a.png)
