### ISSUE TITLE
On hw1 question 6

### ISSUE THREAD

**Issue by aspatic** [hdvvip/CS224W_Winter2021#4]
hello there i am just wondering why do we need a nega-sampling here, isn't nega-sampling only for random walk?

**Comment by hdvvip** [comment]
We are training something like node2vec. Given a node, we want a vector to represent that node.
So, if nodes are connected to each other then their corresponding vectors must have high cosine similarity.
Nodes that are not connected to each other must have low cosine similarity.

We know which nodes are connected to each other by looking at the graph. (positive examples)
Nodes that are not connected to each other are retrieved by nega-sampling. (negative examples)

This idea of Node2Vec is very similar to [Word2Vec](https://arxiv.org/abs/1301.3781).
I recommend read the Word2Vec paper for understanding why we need neg-sampling (negative examples)
