### ISSUE TITLE
problem about colab_1,Q3

### ISSUE THREAD

**Issue by San-ctuary** [hdvvip/CS224W_Winter2021#6]
![image](https://user-images.githubusercontent.com/51828398/147229058-8f485099-9f0a-42e8-ae8d-ffb19f163832.png)
![image](https://user-images.githubusercontent.com/51828398/147229137-4c03b69f-a517-4b0c-80c0-21956569b4f5.png)
I think the equation in the second image is the same as the equation in the first image.Therefore,you do not need to add (1 - B) / N in each loop.
Maybe you can alter your code just like this
```python
for node_neighbor in G.neighbors(node_id):
    node_deg = G.degree[node_neighbor]
    # Notice that all nodes share the same PageRank value r0 at the first iteration
    r1 += beta * r0/node_deg
r1 += (1-beta)*1/N
    
r1 = round(r1, 2)
```

**Comment by hdvvip** [comment]
Yes, you are correct. Thanks for pointing this out. I just fixed that error.
